name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  register-example:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: unionai/flytectl-setup-action@master
      - name: Create Flyte sandbox cluster
        run: | 
          flytectl demo start --source=$(shell pwd)
          # Force refreshing of config file. This will be handled better once we are
          # able to force an update to the config file. Tracked in https://github.com/flyteorg/flyte/issues/3469
          test -f $(HOME)/.flyte/config.yaml && rm $(HOME)/.flyte/config.yaml || true
          flytectl config init --host "localhost:30080" --insecure true
      - uses: ./ # Run the local version of the action.
        with:
          flytesnacks: true
          project: flytesnacks
          version: latest
          domain: development
